author: Tim Videos Community
name: Tim Videos Planet - Developers news
title: Tim Videos Planet - Developers news
description: "News from our best developers, all news aggregated by planet."
url: "http://planet.timvideos.us"
exclude: [Gemfile, Gemfile.lock, planet.yml, README.md, .bundle, vendor]

markdown: kramdown
permalink: pretty

opml:
  source: "planet.yml"
  title: "Tim Videos Feeds"
  outline: 
    title: "Tim Videos"
    text: "Tim Videos"

rss_name: feed.xml
rss_post_limit: 20
rss_allowed_tags: news
rss_allowed_types: standard